/// Import Freezed annotations for code generation
import 'package:freezed_annotation/freezed_annotation.dart';

/// Part files generated by build_runner for Freezed and JSON serialization
part 'image_response.freezed.dart';
part 'image_response.g.dart';

/// Data model representing the response for a random image from the API
/// 
/// This class uses Freezed for immutability and JSON serialization.
/// It contains the URL of the random image fetched from the backend.
@freezed
abstract class ImageResponse with _$ImageResponse {
  /// Private constructor for Freezed to enable custom methods if needed
  const ImageResponse._();
  
  /// Factory constructor to create an ImageResponse instance
  /// 
  /// [url] - The URL string of the random image
  const factory ImageResponse({
    required String url,
  }) = _ImageResponse;

  /// Factory constructor to create an ImageResponse from JSON data
  /// 
  /// Uses the generated fromJson method to deserialize API responses
  factory ImageResponse.fromJson(Map<String, dynamic> json) =>
      _$ImageResponseFromJson(json);
}
